//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<nuclearcraft:compound:2>);
recipes.removeShapeless(<embers:shard_ember>);
recipes.remove(<vehicle:fluid_mixer>);
recipes.remove(<nuclearcraft:rad_x>);
recipes.remove(<nuclearcraft:radaway_slow>);
recipes.remove(<nuclearcraft:radaway>);
recipes.remove(<nuclearcraft:alloy_furnace_idle>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<appliedenergistics2:material:55>);
recipes.remove(<appliedenergistics2:material:36>);
recipes.remove(<modularmachinery:itemmodularium>);
recipes.remove(<clickmachine:auto_clicker>);
recipes.removeShaped(<forestry:ingot_bronze>);
recipes.removeShapeless(<forestry:ingot_bronze>);
recipes.remove(<energyconverters:energy_producer_mj>);
recipes.remove(<pixelmon:aluminum_disc>);
recipes.remove(<opencomputers:storage>);
recipes.remove(<opencomputers:component:2>);
recipes.remove(<opencomputers:component:1>);
recipes.remove(<opencomputers:component>);
recipes.remove(<opencomputers:component:11>);
recipes.remove(<opencomputers:component:10>);
recipes.remove(<opencomputers:component:9>);
recipes.remove(<opencomputers:component:8>);
recipes.remove(<opencomputers:component:7>);
recipes.remove(<opencomputers:component:6>);
recipes.remove(<opencomputers:material:4>);
recipes.remove(<pneumaticcraft:air_compressor>);
recipes.remove(<buildcraftsilicon:assembly_table>);
recipes.remove(<nuclearcraft:part:10>);
recipes.remove(<nuclearcraft:manufactory_idle>);
recipes.remove(<alchemistry:liquifier>);
recipes.remove(<alchemistry:atomizer>);
recipes.remove(<alchemistry:chemical_combiner>);
recipes.remove(<alchemistry:chemical_dissolver>);
recipes.remove(<alchemistry:electrolyzer>);
recipes.remove(<sync:item_placeholder>);
recipes.remove(<opencomputers:material:6>); 
recipes.remove(<opencomputers:material:7>); 
recipes.remove(<opencomputers:material:8>); 
recipes.remove(<opencomputers:material:9>); 
recipes.remove(<opencomputers:material:10>); 
recipes.remove(<opencomputers:material:11>); 
recipes.remove(<projectred-integration:gate:0>); 
recipes.remove(<projectred-integration:gate:1>); 
recipes.remove(<projectred-integration:gate:2>); 
recipes.remove(<projectred-integration:gate:3>); 
recipes.remove(<projectred-integration:gate:4>); 
recipes.remove(<projectred-integration:gate:5>); 
recipes.remove(<projectred-integration:gate:6>); 
recipes.remove(<projectred-integration:gate:7>); 
recipes.remove(<projectred-integration:gate:8>); 
recipes.remove(<projectred-integration:gate:9>); 
recipes.remove(<projectred-integration:gate:10>); 
recipes.remove(<projectred-integration:gate:11>); 
recipes.remove(<projectred-integration:gate:12>); 
recipes.remove(<projectred-integration:gate:13>); 
recipes.remove(<projectred-integration:gate:14>); 
recipes.remove(<projectred-integration:gate:15>); 
recipes.remove(<projectred-integration:gate:16>); 
recipes.remove(<projectred-integration:gate:17>); 
recipes.remove(<projectred-integration:gate:18>); 
recipes.remove(<projectred-integration:gate:19>); 
recipes.remove(<projectred-integration:gate:20>); 
recipes.remove(<projectred-integration:gate:21>); 
recipes.remove(<projectred-integration:gate:22>); 
recipes.remove(<projectred-integration:gate:23>); 
recipes.remove(<projectred-integration:gate:24>); 
recipes.remove(<projectred-integration:gate:25>); 
recipes.remove(<projectred-integration:gate:26>); 
recipes.remove(<projectred-integration:gate:27>); 
recipes.remove(<projectred-integration:gate:28>); 
recipes.remove(<projectred-integration:gate:29>); 
recipes.remove(<projectred-integration:gate:30>); 
recipes.remove(<projectred-integration:gate:31>); 
recipes.remove(<projectred-integration:gate:32>); 
//Don't touch me!
//#Add
recipes.addShapeless(<alchemistry:compound:1001>, [<nuclearcraft:compound:3>]);
recipes.addShapeless(<nuclearcraft:compound:3>, [<alchemistry:compound:1001>]);
recipes.addShapeless(<nuclearcraft:compound:2>, [<minecraft:redstone>, <minecraft:glowstone_dust>, <nuclearcraft:uranium:9>]);
recipes.addShapeless(<nuclearcraft:compound:2>, [<minecraft:redstone>, <minecraft:glowstone_dust>, <nuclearcraft:uranium:8>]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:7>, [[<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyoutputhatch:6>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:6>, [[<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyoutputhatch:5>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:5>, [[<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyoutputhatch:4>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:4>, [[<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyoutputhatch:3>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:3>, [[<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyoutputhatch:2>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:2>, [[<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyoutputhatch:1>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:7>, [[<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyinputhatch:6>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:6>, [[<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyinputhatch:5>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:5>, [[<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyinputhatch:4>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:4>, [[<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyinputhatch:3>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:3>, [[<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyinputhatch:2>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:2>, [[<minecraft:redstone>, <minecraft:repeater>, <minecraft:redstone>],[<minecraft:redstone_block>, <modularmachinery:blockenergyinputhatch:1>, <minecraft:redstone_block>], [<minecraft:redstone>, <minecraft:redstone_block>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:7>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:6>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:6>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:5>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:5>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:4>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:4>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:3>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:3>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:2>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:2>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidinputhatch:1>, <modularmachinery:itemmodularium>], [<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:7>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:6>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:6>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:5>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:5>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:4>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:4>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:3>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:3>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:2>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:2>, [[<minecraft:bucket>, <modularmachinery:itemmodularium>, <minecraft:bucket>],[<modularmachinery:itemmodularium>, <modularmachinery:blockfluidoutputhatch:1>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:6>, [[<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:5>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:5>, [[<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:4>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:4>, [[<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:3>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:3>, [[<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:2>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:2>, [[<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>],[<modularmachinery:itemmodularium>, <modularmachinery:blockoutputbus:1>, <modularmachinery:itemmodularium>], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:6>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:5>, <modularmachinery:itemmodularium>], [<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:5>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:4>, <modularmachinery:itemmodularium>], [<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:4>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:3>, <modularmachinery:itemmodularium>], [<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:3>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:2>, <modularmachinery:itemmodularium>], [<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>]]);
recipes.addShaped(<modularmachinery:blockinputbus:2>, [[null, <minecraft:hopper>, null],[<modularmachinery:itemmodularium>, <modularmachinery:blockinputbus:1>, <modularmachinery:itemmodularium>], [<minecraft:chest>, <modularmachinery:itemmodularium>, <minecraft:chest>]]);
recipes.addShaped(<modularmagic:blockstarlightproviderinput>, [[null, <astralsorcery:blockcelestialcollectorcrystal>, null],[<astralsorcery:itemcoloredlens:2>, <modularmachinery:blockcasing>, <astralsorcery:itemcoloredlens:1>], [null, <astralsorcery:blocklens>, null]]);
recipes.addShaped(<modularmachinery:itemblueprint>, [[<modularmachinery:itemmodularium>, <pneumaticcraft:plastic>, <astralsorcery:itemcraftingcomponent:4>],[null, null, null], [null, null, null]]);
recipes.addShaped(<pixelmon:pc>, [[<immersiveengineering:metal:31>, <minecraft:glass_pane>, <immersiveengineering:metal:31>],[<immersiveengineering:metal:31>, <minecraft:redstone_lamp>, <immersiveengineering:metal:31>], [<immersiveengineering:metal:31>, <minecraft:redstone>, <immersiveengineering:metal:31>]]);
recipes.addShaped(<pixelmon:healer>, [[<immersiveengineering:metal:31>, <minecraft:iron_ingot>, <immersiveengineering:metal:31>],[<minecraft:iron_ingot>, <minecraft:diamond>, <minecraft:iron_ingot>], [<immersiveengineering:metal:31>, <minecraft:iron_ingot>, <immersiveengineering:metal:31>]]);
recipes.addShaped(<pixelmon:warp_plate> * 2, [[<soot:ingot_antimony>, <appliedenergistics2:material:48>, <soot:ingot_antimony>],[<botania:manaresource:8>, <advancedrocketry:warpcore>, <botania:manaresource:8>], [<immersiveengineering:metal:8>, <appliedenergistics2:material:48>, <immersiveengineering:metal:8>]]);
recipes.addShaped(<cookingforblockheads:cow_jar>, [[null, null, <minecraft:anvil>],[null, null, <minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}})], [null, null, <cookingforblockheads:milk_jar>]]);
recipes.addShaped(<cookingforblockheads:cow_jar>, [[null, <minecraft:anvil>, null],[null, <minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}}), null], [null, <cookingforblockheads:milk_jar>, null]]);
recipes.addShaped(<cookingforblockheads:cow_jar>, [[<minecraft:anvil>, null, null],[<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}}), null, null], [<cookingforblockheads:milk_jar>, null, null]]);
recipes.addShaped(<nuclearcraft:alloy_furnace_idle>, [[<nuclearcraft:part>, <buildcraftsilicon:redstone_chipset>, <nuclearcraft:part>],[<immersiveengineering:metal:8>, <immersiveengineering:metal_device1:1>, <immersiveengineering:metal:8>], [<nuclearcraft:part>, <nuclearcraft:part:4>, <nuclearcraft:part>]]);
recipes.addShaped(<minecraft:stick> * 16, [[null, null, null],[null, null, <ore:logWood>], [null, null, <ore:logWood>]]);
recipes.addShaped(<minecraft:stick> * 16, [[null, null, null],[null, <ore:logWood>, null], [null, <ore:logWood>, null]]);
recipes.addShaped(<minecraft:stick> * 16, [[null, null, null],[<ore:logWood>, null, null], [<ore:logWood>, null, null]]);
recipes.addShaped(<minecraft:stick> * 16, [[null, null, <ore:logWood>],[null, null, <ore:logWood>], [null, null, null]]);
recipes.addShaped(<minecraft:stick> * 16, [[<ore:logWood>, null, null],[<ore:logWood>, null, null], [null, null, null]]);
recipes.addShaped(<minecraft:stick> * 16, [[null, <ore:logWood>, null],[null, <ore:logWood>, null], [null, null, null]]);
recipes.addShaped(<appliedenergistics2:controller>, [[<immersiveengineering:storage:8>, <appliedenergistics2:material:12>, <immersiveengineering:storage:8>],[<pneumaticcraft:printed_circuit_board>, <opencomputers:component:2>, <pneumaticcraft:printed_circuit_board>], [<appliedenergistics2:sky_stone_block>, <appliedenergistics2:material:12>, <appliedenergistics2:sky_stone_block>]]);
recipes.addShaped(<appliedenergistics2:material:55>, [[<minecraft:dye:4>, <appliedenergistics2:material:23>, <minecraft:dye:4>],[<appliedenergistics2:material:54>, <pneumaticcraft:capacitor>, <appliedenergistics2:material:54>], [<minecraft:dye:4>, <appliedenergistics2:material:54>, <minecraft:dye:4>]]);
recipes.addShaped(<appliedenergistics2:material:36>, [[<minecraft:redstone>, <appliedenergistics2:material:23>, <minecraft:redstone>],[<appliedenergistics2:material:35>, <pneumaticcraft:capacitor>, <appliedenergistics2:material:35>], [<minecraft:redstone>, <appliedenergistics2:material:35>, <minecraft:redstone>]]);
recipes.addShaped(<modularmachinery:itemmodularium>, [[<minecraft:gold_ingot>, <immersiveengineering:metal:8>, <minecraft:gold_ingot>],[<immersiveengineering:metal:8>, <minecraft:redstone>, <immersiveengineering:metal:8>], [<minecraft:redstone>, <minecraft:glowstone_dust>, <minecraft:redstone>]]);
recipes.addShaped(<clickmachine:auto_clicker>, [[<minecraft:stone:3>, <minecraft:stone:3>, <minecraft:stone:3>],[<minecraft:stone:3>, <minecraft:ender_pearl>, <minecraft:stone:3>], [<minecraft:stone:3>, <minecraft:redstone_block>, <minecraft:stone:3>]]);
recipes.addShaped(<energyconverters:energy_producer_mj>, [[<minecraft:stone>, <railcraft:gear:1>, <minecraft:stone>],[<immersiveengineering:metal_decoration0:5>, <buildcrafttransport:pipe_wood_item>, <minecraft:gold_ingot>], [<minecraft:stone>, <railcraft:gear:1>, <minecraft:stone>]]);
recipes.addShaped(<minecraft:chest> * 4, [[<ore:logWood>, <ore:logWood>, <ore:logWood>],[<ore:logWood>, null, <ore:logWood>], [<ore:logWood>, <ore:logWood>, <ore:logWood>]]);
recipes.addShaped(<pixelmon:aluminum_disc>, [[null, null, null],[<immersiveengineering:metal:1>, <immersiveengineering:metal:1>, <immersiveengineering:metal:1>], [null, null, null]]);
recipes.addShaped(<pneumaticcraft:air_compressor>, [[<pneumaticcraft:ingot_iron_compressed>, <pneumaticcraft:ingot_iron_compressed>, <pneumaticcraft:ingot_iron_compressed>],[<pneumaticcraft:ingot_iron_compressed>, null, <pneumaticcraft:pressure_tube>], [<pneumaticcraft:ingot_iron_compressed>, <immersiveengineering:metal_device1:1>, <pneumaticcraft:ingot_iron_compressed>]]);
recipes.addShaped(<buildcraftsilicon:assembly_table>, [[<minecraft:obsidian>, <magneticraft:heavy_plates:6>, <minecraft:obsidian>],[<immersiveengineering:material:2>, <minecraft:redstone>, <immersiveengineering:material:2>], [<minecraft:obsidian>, <buildcraftcore:gear_diamond>, <minecraft:obsidian>]]);
recipes.addShaped(<nuclearcraft:part:10>, [[<immersiveengineering:metal:2>, <immersiveengineering:metal:8>, <immersiveengineering:metal:2>],[<immersiveengineering:metal:8>, <immersiveengineering:metal_decoration0:5>, <immersiveengineering:metal:8>], [<immersiveengineering:metal:2>, <immersiveengineering:metal:8>, <immersiveengineering:metal:2>]]);
recipes.addShaped(<nuclearcraft:manufactory_idle>, [[<immersiveengineering:metal:2>, <buildcraftsilicon:redstone_chipset>, <immersiveengineering:metal:2>],[<minecraft:obsidian>, <projectred-integration:gate:13>, <minecraft:obsidian>], [<immersiveengineering:metal:2>, <nuclearcraft:part:4>, <immersiveengineering:metal:2>]]);
recipes.addShaped(<alchemistry:liquifier>, [[<minecraft:iron_ingot>, <buildcraftsilicon:redstone_chipset:4>, <minecraft:iron_ingot>],[<minecraft:stone_pressure_plate>, <minecraft:iron_ingot>, <minecraft:stone_pressure_plate>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<alchemistry:atomizer>, [[<minecraft:iron_ingot>, <buildcraftsilicon:redstone_chipset:4>, <minecraft:iron_ingot>],[<minecraft:stone_pressure_plate>, <minecraft:gold_ingot>, <minecraft:stone_pressure_plate>], [<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>]]);
recipes.addShaped(<alchemistry:chemical_combiner>, [[<minecraft:iron_ingot>, <minecraft:diamond>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <minecraft:obsidian>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <projectred-integration:gate:13>, <minecraft:iron_ingot>]]);
recipes.addShaped(<alchemistry:chemical_dissolver>, [[<minecraft:iron_ingot>, <projectred-integration:gate:13>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <buildcraftsilicon:redstone_chipset:4>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <projectred-integration:gate:13>, <minecraft:iron_ingot>]]);
recipes.addShaped(<alchemistry:electrolyzer>, [[<minecraft:iron_ingot>, <buildcraftsilicon:redstone_chipset:3>, <minecraft:iron_ingot>],[<minecraft:gold_ingot>, <buildcraftsilicon:redstone_chipset:3>, <minecraft:gold_ingot>], [<minecraft:iron_ingot>, <projectred-integration:gate:13>, <minecraft:iron_ingot>]]);
recipes.addShaped(<sync:item_placeholder>, [[<advancedrocketry:ic:3>, <pixelmon:cloner_cord>, <advancedrocketry:ic:2>],[<opencomputers:material:11>, <appliedenergistics2:material:24>, <opencomputers:material:11>], [<opencomputers:material:10>, <buildcraftsilicon:redstone_chipset:4>, <opencomputers:material:10>]]);
recipes.addShaped(<opencomputers:material:6> * 8, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[<minecraft:gold_nugget>, <projectred-core:resource_item:320>, <minecraft:gold_nugget>], [null, <buildcraftsilicon:redstone_chipset>, null]]);
recipes.addShaped(<opencomputers:material:7> * 8, [[<minecraft:iron_nugget>, <minecraft:iron_nugget>, <minecraft:iron_nugget>],[<buildcraftsilicon:redstone_chipset>, <opencomputers:material:6>, <buildcraftsilicon:redstone_chipset>], [<minecraft:iron_nugget>, <minecraft:iron_nugget>, <minecraft:iron_nugget>]]);
recipes.addShaped(<opencomputers:material:9> * 2, [[<opencomputers:material:29>, <opencomputers:material:29>, <opencomputers:material:29>],[<buildcraftsilicon:redstone_chipset:4>, <opencomputers:material:8>, <buildcraftsilicon:redstone_chipset:4>], [<opencomputers:material:29>, <opencomputers:material:29>, <opencomputers:material:29>]]);
recipes.addShaped(<opencomputers:material:8> * 4, [[<minecraft:gold_nugget>, <minecraft:gold_nugget>, <minecraft:gold_nugget>],[<buildcraftsilicon:redstone_chipset:2>, <opencomputers:material:7>, <buildcraftsilicon:redstone_chipset:2>], [<minecraft:gold_nugget>, <minecraft:gold_nugget>, <minecraft:gold_nugget>]]);
recipes.addShaped(<opencomputers:material:10>, [[<projectred-integration:gate:5>, <projectred-integration:gate:3>, <projectred-integration:gate:5>],[<projectred-integration:gate:24>, <buildcraftsilicon:redstone_chipset:4>, <projectred-integration:gate>], [<minecraft:iron_nugget>, <projectred-integration:gate:3>, <minecraft:iron_nugget>]]);
recipes.addShaped(<opencomputers:material:11>, [[<minecraft:gold_nugget>, <buildcraftsilicon:redstone_chipset>, <minecraft:gold_nugget>],[<opencomputers:material:6>, <projectred-integration:gate:17>, <opencomputers:material:6>], [<minecraft:gold_nugget>, <opencomputers:material:6>, <minecraft:gold_nugget>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:zombie"}}), [[<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>],[<minecraft:rotten_flesh>, <minecraft:egg>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:witch"}}), [[<minecraft:sugar>, <minecraft:glowstone_dust>, <minecraft:sugar>],[<minecraft:redstone>, <minecraft:egg>, <minecraft:redstone>], [<minecraft:sugar>, <minecraft:glowstone_dust>, <minecraft:sugar>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:sheep"}}), [[<minecraft:mutton>, <minecraft:wool>, <minecraft:mutton>],[<minecraft:wool>, <minecraft:egg>, <minecraft:wool>], [<minecraft:mutton>, <minecraft:wool>, <minecraft:mutton>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:pig"}}), [[<minecraft:porkchop>, <minecraft:porkchop>, <minecraft:porkchop>],[<minecraft:porkchop>, <minecraft:egg>, <minecraft:porkchop>], [<minecraft:porkchop>, <minecraft:porkchop>, <minecraft:porkchop>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:skeleton"}}), [[<minecraft:arrow>, <minecraft:bone>, <minecraft:arrow>],[<minecraft:bone>, <minecraft:egg>, <minecraft:bone>], [<minecraft:arrow>, <minecraft:bone>, <minecraft:arrow>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:slime"}}), [[<minecraft:slime_ball>, <minecraft:slime_ball>, <minecraft:slime_ball>],[<minecraft:slime_ball>, <minecraft:egg>, <minecraft:slime_ball>], [<minecraft:slime_ball>, <minecraft:slime_ball>, <minecraft:slime_ball>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:magma_cube"}}), [[<minecraft:slime_ball>, <minecraft:magma_cream>, <minecraft:slime_ball>],[<minecraft:magma_cream>, <minecraft:egg>, <minecraft:magma_cream>], [<minecraft:slime_ball>, <minecraft:magma_cream>, <minecraft:slime_ball>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:guardian"}}), [[<minecraft:prismarine_crystals>, <minecraft:prismarine_shard>, <minecraft:prismarine_crystals>],[<minecraft:prismarine_shard>, <minecraft:egg>, <minecraft:prismarine_shard>], [<minecraft:prismarine_crystals>, <minecraft:prismarine_shard>, <minecraft:prismarine_crystals>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:ghast"}}), [[<minecraft:gunpowder>, <minecraft:ghast_tear>, <minecraft:gunpowder>],[<minecraft:ghast_tear>, <minecraft:egg>, <minecraft:ghast_tear>], [<minecraft:gunpowder>, <minecraft:ghast_tear>, <minecraft:gunpowder>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:shulker"}}), [[<minecraft:purpur_block>, <minecraft:shulker_shell>, <minecraft:purpur_block>],[<minecraft:shulker_shell>, <minecraft:egg>, <minecraft:shulker_shell>], [<minecraft:purpur_block>, <minecraft:shulker_shell>, <minecraft:purpur_block>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:enderman"}}), [[<minecraft:purpur_block>, <minecraft:ender_pearl>, <minecraft:purpur_block>],[<minecraft:ender_pearl>, <minecraft:egg>, <minecraft:ender_pearl>], [<minecraft:purpur_block>, <minecraft:ender_pearl>, <minecraft:purpur_block>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:creeper"}}), [[<minecraft:gunpowder>, <minecraft:gunpowder>, <minecraft:gunpowder>],[<minecraft:gunpowder>, <minecraft:egg>, <minecraft:gunpowder>], [<minecraft:gunpowder>, <minecraft:gunpowder>, <minecraft:gunpowder>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cow"}}), [[<minecraft:leather>, <minecraft:beef>, <minecraft:leather>],[<minecraft:beef>, <minecraft:egg>, <minecraft:beef>], [<minecraft:leather>, <minecraft:beef>, <minecraft:leather>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:chicken"}}), [[<minecraft:egg>, <minecraft:feather>, <minecraft:egg>],[<minecraft:feather>, <minecraft:egg>, <minecraft:feather>], [<minecraft:egg>, <minecraft:feather>, <minecraft:egg>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:spider"}}), [[<minecraft:spider_eye>, <minecraft:string>, <minecraft:spider_eye>],[<minecraft:string>, <minecraft:egg>, <minecraft:string>], [<minecraft:spider_eye>, <minecraft:string>, <minecraft:spider_eye>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:cave_spider"}}), [[<minecraft:spider_eye>, <minecraft:string>, <minecraft:spider_eye>],[<minecraft:string>, <minecraft:egg>, <minecraft:string>], [<minecraft:spider_eye>, <minecraft:potion>, <minecraft:spider_eye>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id: "minecraft:blaze"}}), [[<minecraft:blaze_rod>, <minecraft:blaze_rod>, <minecraft:blaze_rod>],[<minecraft:blaze_rod>, <minecraft:egg>, <minecraft:blaze_rod>], [<minecraft:blaze_rod>, <minecraft:blaze_rod>, <minecraft:blaze_rod>]]);
//File End
